#include "vkit/core/api.hpp"
#define VMA_NULLABLE
#define VMA_NOT_NULL
TKIT_COMPILER_WARNING_IGNORE_PUSH()
TKIT_GCC_WARNING_IGNORE("-Wunused-parameter")
TKIT_GCC_WARNING_IGNORE("-Wunused-variable")
TKIT_GCC_WARNING_IGNORE("-Wunused-function")
TKIT_GCC_WARNING_IGNORE("-Wmissing-field-initializers")
TKIT_CLANG_WARNING_IGNORE("-Wunused-parameter")
TKIT_CLANG_WARNING_IGNORE("-Wunused-variable")
TKIT_CLANG_WARNING_IGNORE("-Wunused-function")
TKIT_CLANG_WARNING_IGNORE("-Wmissing-field-initializers")
TKIT_MSVC_WARNING_IGNORE(4100)
TKIT_MSVC_WARNING_IGNORE(4189)
TKIT_MSVC_WARNING_IGNORE(4505)
TKIT_MSVC_WARNING_IGNORE(4351)
TKIT_MSVC_WARNING_IGNORE(4127)
TKIT_MSVC_WARNING_IGNORE(4324)
#include <vk_mem_alloc.h>
TKIT_COMPILER_WARNING_IGNORE_POP()